### ISSUE TITLE
Migrate discuss.asciidoctor.org to Discourse

### ISSUE THREAD

**Issue by mojavelinux** [asciidoctor/asciidoctor.org#304]
Migrate the discussion list at discuss.asciidoctor.org to a Discourse instance running under the same domain name.

**Comment by mojavelinux** [comment]
We've reached out to DigitalOcean and they have offered to sponsor the hosting of the Discourse forums (on a 2GB server). I'll work with @Mogztter to get it setup. If anyone else is interested to help manage the server, please come forward.

**Comment by Mogztter** [comment]
@mojavelinux Are you waiting for DigitalOcean to give you access to a server?

**Comment by mojavelinux** [comment]
@Mogztter I got tied up with a contract, so it was sitting on the backburner. I just created an Asciidoctor team and sent you an invite. There is a $240 credit applied to the account. You can now proceed with creating a Droplet and getting a vanilla Discourse instance running. If you'd like, I can create a staging subdomain that we can use to point to it until we are ready to migrate (e.g., discourse.asciidoctor.org). Just let me know.

Anyone else who would like to be involved in the sysadmin part, just let me know and I'll get you lined up.

**Comment by Mogztter** [comment]
@mojavelinux Instance is created. I just sent you an invitation. Until the DNS is up, you will need to add the following line in your `/etc/hosts` file:

```
45.55.159.229 discourse.asciidoctor.org
```

**Comment by Mogztter** [comment]
Someone is working on a Nabble importer: https://github.com/discourse/discourse/blob/master/script/import_scripts/nabble.rb

**Comment by mojavelinux** [comment]
Fantastic!

> Do we still want to import Nabble posts into Discourse ?

I'd like to at least try. There's a lot of super valuable information in those threads that are still ongoing topics. I think doing a read-only would interrupt the flow of the discussion. I'm not too concerned about losing some formatting because the value is in the content. How to handle the URLs is a bit trickier.

If we do decide that we would need both, I'd prefer to have a gradual migration where both are read-write but we just keep reminding people of the new location. But the idea of leaving behind posts in Nabble feels incomplete.

I'll keep thinking about it and bounce some ideas off Sarah as well.

**Comment by Mogztter** [comment]
> I'd like to at least try. There's a lot of super valuable information in those threads that are still ongoing topics. I think doing a read-only would interrupt the flow of the discussion. I'm not too concerned about losing some formatting because the value is in the content.

I agree but the content is messed up with HTML formatting, so we need to extract the valuable information from the mess :smile: 

I can try to run the importer so you can see if the formatting is well enough ?

> How to handle the URLs is a bit trickier.

URL rewriting or redirection could do the job but I'm not a SEO expert.

> If we do decide that we would need both, I'd prefer to have a gradual migration where both are read-write but we just keep reminding people of the new location.

I'd rather not

> But the idea of leaving behind posts in Nabble feels incomplete. I'll keep thinking about it and bounce some ideas off Sarah as well.

Ok

**Comment by Mogztter** [comment]
http://blog.discourse.org/2015/09/discourse-1-4-released/

**Comment by Mogztter** [comment]
Sorry this issue has been in my todo for a long time.
To summarize migrating all the content and users from Nabble is pretty straight froward. The tricky part is formatting the content and rewriting URLs (more specifically rewriting links in Nabble's posts that reference other Nabble's posts).

@mojavelinux If you want I can import content from Nabble with the latest version of the [import script](https://github.com/discourse/discourse/blob/master/script/import_scripts/nabble.rb) so you can see the end result and decide if we should migrate now or spend time tweaking the import script ?

Apart from that, Discourse now offers free hosting for Open Source project. 

**Minimum Requirements**
 * Must be hosted on GitHub
 ** 2000+ stars
 ** 30+ contributors
 * Your project has a clear need for discussions (see FAQ below)
 * Please understand that approval is ultimately at our discretion as we work out the details of this program.

http://blog.discourse.org/2016/03/free-discourse-forum-hosting-for-community-friendly-github-projects/

**Comment by Mogztter** [comment]
I've imported again a backup from Nabble (2014-09-07). There's no DNS attached yet, but you can add the following line in your `/etc/hosts` file:

```
45.55.159.229 discourse.asciidoctor.org
```

If you browser to http://discourse.asciidoctor.org/ you should see:

![discourse](https://cloud.githubusercontent.com/assets/333276/17904115/50e18fa6-696e-11e6-8080-13d9a79095bd.png)

IMPORTANT: This is a staging environment! Emails are anonymized in this backup so you will not be able to retrieve your Nabble's account (even if you use the same email address). But feel free to create an account and test Discourse.

We are currently running version 1.6.1 of Discourse with mostly the default configuration.

@mojavelinux If you create an account with your email address you should be administrator.

**Comment by Mogztter** [comment]
**TODO:**

 * [ ] Create a DNS `discuss-staging.asciidoctor.org` to `45.55.159.229`
 * [ ] Create a fresh backup of Nabble
 * [ ] Import data
 * [ ] Configure Discourse
   * [ ] Create categories ?
   * [ ] Pin topics ?
   * [ ] Set up reply via email support (https://meta.discourse.org/t/set-up-reply-via-email-support/14003)
 * [ ] Test, test and test
 * [ ] Invite few community members to test
 * [ ] Make an announcement
   * [ ] Explain how to enable mailing list mode on Discourse
 * [ ] Archive Nabble (read only)
 * [ ] Reset Discourse
 * [ ] Create a fresh backup of Nabble (without anonymization)
 * [ ] Update DNS `discuss.asciidoctor.org` to `45.55.159.229`
 * [ ] Configure Discourse
 * [ ] Send invites for everyone
 * [ ] Enjoy :tada: :beers: :smile:

**Comment by mojavelinux** [comment]
I'll get on (1) and (2) asap. Stay tuned.

**Comment by Mogztter** [comment]
The Nabble UI gives me migrane :mask: 
I've updated Discourse to 1.6.4+2  http://discourse.asciidoctor.org/

**Comment by shahryareiv** [comment]
Address http://discourse.asciidoctor.org/  shows "Server Not Found".

As I posted in the forum, an easy alternative can be to open a GitHub project called Asciidoctor-Discussion and discuss through issues  tab. Probably more integration with Asciidoctor projects, easier maintenance, less spam, and good enough notification features .

**Comment by Mogztter** [comment]
@shahryareiv Did you configure your `hosts` file with `45.55.159.229 discourse.asciidoctor.org` ?

**Comment by shahryareiv** [comment]
@Mogztter , Sorry I misunderstood the discussions above and thought things are finalized in October. Now I can see the site. Still I think the github-as-forum might be an alternative (if past discussions migration is not critical).

**Comment by Mogztter** [comment]
> Still I think the github-as-forum might be an alternative

github-as-forum is an interesting idea because we will not have to run a server.
If we really don't want to run a server, we could also let Discourse hosts it for us: https://payments.discourse.org/buy/



> if past discussions migration is not critical

I think migration is pretty important because we have a lot of useful content on discuss.asciidoctor.org

**Comment by Mogztter** [comment]
> We’ve had an informal policy of providing free hosting for other open source tools that Discourse directly relies on
https://blog.discourse.org/2016/03/free-discourse-forum-hosting-for-community-friendly-github-projects/

Time to integrate Asciidoctor in Discourse :rofl:

**Comment by mojavelinux** [comment]
5 years on, I'm pleased to say that Zulip has won our :heart: and :brain:. [Zulip](https://zulip.com) is a modern, unified collaboration platform for distributed teams. On the one hand, it serves as a chat, allowing you to sign in and interact with others in real time. On the other hand, it also provides an integrated search, sends email notifications, and can be browsed without an account, making it double as a mailing list. It's the best of both worlds.

We've been using Zulip now for over a year. We can say with confidence that it has proven to give us exactly what we need to communicate with fellow community members. Zulip also has the benefit of being 100% open source plus indefinite hosting (without renewal hassle) for our open source project. You can read more about our experience with Zulip and why we love it in our case study, which was recently published at https://zulip.com/case-studies/asciidoctor/

I want to thank @Mogztter for exploring and prototyping the migration to Discourse. That exercise helped us understand our requirements so that when Zulip came along, we were able to recognize it as the solution we've been searching (and yearning) for.

As of now, the Asciidoctor discussion list is read only for new posts. We will keep the archives there indefinitely. All new discussions should be directed at the Zulip-powered project chat at https://chat.asciidoctor.org (which redirects to an instance provided by the Zulip project).

See you in the project chat!
